### ISSUE TITLE
Can't use stream upload

### ISSUE THREAD

**Issue by dev-cyprium** [ex-aws/ex_aws_s3#42]
### Environment
```
$ elixir --version
Erlang/OTP 21 [erts-10.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.4 (compiled with Erlang/OTP 20)
```
```
$ mix deps | grep ex_aws
* ex_aws 2.0.2 (Hex package) (mix)
  locked at 2.1.0 (ex_aws) b9265152
* ex_aws_s3 2.0.0 (Hex package) (mix)
  locked at 2.0.1 (ex_aws_s3) 9e09366e
```
* HTTP client version. IE for hackney do `mix deps | grep hackney
```
mix deps | grep hackney
* hackney 1.10.1 (Hex package) (rebar3)
  locked at 1.10.1 (hackney) c38d0ca5
```

### Current behavior
After trying to follow the documentation for uploading a big file in stream fassion:
```Elixir
path = "/path/to/file"
key  = "/path/to/s3"
bucket = "bucket.name"

path
    |> S3.Upload.stream_file
    |> S3.upload(bucket, key)
    |> ExAws.request!
```

I get the following stacktrace:
```
** (FunctionClauseError) no function clause matching in :raw_file_io_raw.open_layer/3    
    
    The following arguments were given to :raw_file_io_raw.open_layer/3:
    
        # 1
        "/path/to/file"
    
        # 2
        [:read, {:read_ahead, 65536}, :binary, :binary]
    
        # 3
        [:raw, :raw]
     
    (kernel) raw_file_io_raw.erl:24: :raw_file_io_raw.open_layer/3
    (elixir) lib/file/stream.ex:78: anonymous fn/3 in Enumerable.File.Stream.reduce/3
    (elixir) lib/stream.ex:1362: anonymous fn/5 in Stream.resource/3
    (elixir) lib/stream.ex:1553: Enumerable.Stream.do_each/4
    (elixir) lib/task/supervised.ex:306: Task.Supervised.stream_reduce/7
    (elixir) lib/enum.ex:2979: Enum.reverse/1
    (elixir) lib/enum.ex:2613: Enum.to_list/1
    (ex_aws_s3) lib/ex_aws/s3/upload.ex:89: ExAws.Operation.ExAws.S3.Upload.perform/2
    (ex_aws) lib/ex_aws.ex:61: ExAws.request!/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
```

### Expected behavior
I'd like for the file to just be uploaded in chunks.

**Comment by dev-cyprium** [comment]
The problem was my local elixir/erlang installation, not an issue with the library.
