### ISSUE TITLE
Using a S3 request call without bang still raises an exception

### ISSUE THREAD

**Issue by PinheiroRodrigo** [ex-aws/ex_aws_s3#5]
### Environment
* ExAws version 2.0.1, ExAwsS3 version 2.0.0
### Current behavior
I'm uploading files to S3, and i have a poor internet connection and my intention is that this code does not raise an exception (that's why i use `ExAws.request` without a bang)
```
file
    |> ExAws.S3.Upload.stream_file
    |> ExAws.S3.upload(bucket_name, path, timeout: :infinity)
    |> ExAws.request

```
However, in the flow, `upload_chunk!` is called, which has a request call with a bang inside, and in some cases, this error occurs:
```
** (EXIT from #PID<0.444.0>) evaluator process exited with reason: an exception was raised:
    ** (ExAws.Error) ExAws Request Error!

{:error, {:http_error, 400, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>C55655BDD4AA47EF</RequestId><HostId>ltnii8mbF9VrPPUaXUlaFZi10d9oi1B2u2ZRLjEqHfL0XlLPzDpQL7Lms991yg4ylsSNo/Vwz32XWcOgsW+wa0GAMqoIL0R1</HostId></Error>", headers: [{"Date", "Tue, 14 Nov 17 13:07:20 GMT"}, {"Connection", "close"}, {"Transfer-Encoding", "chunked"}, {"x-amz-id-2", "ltnii8mbF9VrPPUaXUlaFZi10d9oi1B2u2ZRLjEqHfL0XlLPzDpQL7Lms991yg4ylsSNo/Vwz32XWcOgsW+wa0GAMqoIL0R1"}, {"x-amz-request-id", "C55655BDD4AA47EF"}, {"Content-Type", "application/xml"}], status_code: 400}}}

        (ex_aws) lib/ex_aws.ex:46: ExAws.request!/2
        (ex_aws) lib/ex_aws/s3/upload.ex:67: ExAws.S3.Upload.upload_chunk!/3
        (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
Is there a workaround for this or i'm missing something ?

### Expected behavior
If the request fails, returns a tuple {:error, error}.

**Comment by benwilson512** [comment]
This is because you don't have `sweet_xml` installed. It can't parse the result coming back from AWS.
