### ISSUE TITLE
list_objects/1 with stream!/0  fails at end of "page" (after first 1000)

### ISSUE THREAD

**Issue by ryanwinchester** [ex-aws/ex_aws_s3#93]
* Do not use the issues tracker for help or support (try Elixir Forum, Slack, IRC, etc.)
* Questions about how to contribute are fine.

### Environment

* Elixir & Erlang versions 1.10.2
* ExAws version 2.1.3
* HTTP client version 1.16.0

### Current behavior

```elixir
ExAws.S3.list_objects("mybucket") |> ExAws.stream!()
```

After we finish processing the 1000th object, we get:

```
** (ExAws.Error) ExAws Request Error!
{:error, {:http_error, 403, %{body: “<?xml version=\“1.0\” encoding=\“UTF-8\“?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>******</AWSAccessKeyId><StringToSign>AWS4-HMAC-SHA256\n20200807T233025Z\n20200807/us-east-2/s3/aws4_request\n7669d942e1f83a2c6061b9bad8a7755f6e441ec952cfc01de30327cadef84a45</StringToSign><SignatureProvided>93f03b3e14236e620bfcfcf78cfc95e6deaff6a8870687b54834998596e47b3b</SignatureProvided><StringToSignBytes>41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 32 30 30 38 30 37 54 32 33 33 30 32 35 5a 0a 32 30 32 30 30 38 30 37 2f 75 73 2d 65 61 73 74 2d 32 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 37 36 36 39 64 39 34 32 65 31 66 38 33 61 32 63 36 30 36 31 62 39 62 61 64 38 61 37 37 35 35 66 36 65 34 34 31 65 63 39 35 32 63 66 63 30 31 64 65 33 30 33 32 37 63 61 64 65 66 38 34 61 34 35</StringToSignBytes><CanonicalRequest>GET\n/cariq-calamp-logs/\nmarker=2019-07-26%2B03%3A18%3A08.345831\nhost:s3.us-east-2.amazonaws.com\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:20200807T233025Z\n\nhost;x-amz-content-sha256;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</CanonicalRequest><CanonicalRequestBytes>47 45 54 0a 2f 63 61 72 69 71 2d 63 61 6c 61 6d 70 2d 6c 6f 67 73 2f 0a 6d 61 72 6b 65 72 3d 32 30 31 39 2d 30 37 2d 32 36 25 32 42 30 33 25 33 41 31 38 25 33 41 30 38 2e 33 34 35 38 33 31 0a 68 6f 73 74 3a 73 33 2e 75 73 2d 65 61 73 74 2d 32 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 0a 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3a 65 33 62 30 63 34 34 32 39 38 66 63 31 63 31 34 39 61 66 62 66 34 63 38 39 39 36 66 62 39 32 34 32 37 61 65 34 31 65 34 36 34 39 62 39 33 34 63 61 34 39 35 39 39 31 62 37 38 35 32 62 38 35 35 0a 78 2d 61 6d 7a 2d 64 61 74 65 3a 32 30 32 30 30 38 30 37 54 32 33 33 30 32 35 5a 0a 0a 68 6f 73 74 3b 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3b 78 2d 61 6d 7a 2d 64 61 74 65 0a 65 33 62 30 63 34 34 32 39 38 66 63 31 63 31 34 39 61 66 62 66 34 63 38 39 39 36 66 62 39 32 34 32 37 61 65 34 31 65 34 36 34 39 62 39 33 34 63 61 34 39 35 39 39 31 62 37 38 35 32 62 38 35 35</CanonicalRequestBytes><RequestId>A192E91CD4669824</RequestId><HostId>MC9cG0H9QIUgT39rQjnArUgfDoX55P9PEAJTZMYG4KXS5lJVmCxEg7UIm+NGzBo4Nqlxd5VrSpI=</HostId></Error>“, headers: [{“x-amz-bucket-region”, “us-east-2"}, {“x-amz-request-id”, “A192E91CD4669824"}, {“x-amz-id-2”, “MC9cG0H9QIUgT39rQjnArUgfDoX55P9PEAJTZMYG4KXS5lJVmCxEg7UIm+NGzBo4Nqlxd5VrSpI=“}, {“Content-Type”, “application/xml”}, {“Transfer-Encoding”, “chunked”}, {“Date”, “Fri, 07 Aug 2020 23:30:28 GMT”}, {“Server”, “AmazonS3"}], status_code: 403}}}
    (ex_aws 2.1.3) lib/ex_aws.ex:66: ExAws.request!/2
    (ex_aws_s3 2.0.2) lib/ex_aws/s3/lazy.ex:7: anonymous fn/4 in ExAws.S3.Lazy.stream_objects!/3
    (ex_aws_s3 2.0.2) lib/ex_aws/s3/lazy.ex:14: anonymous fn/2 in ExAws.S3.Lazy.stream_objects!/3
    (elixir 1.10.2) lib/stream.ex:1421: Stream.do_resource/5
    (elixir 1.10.2) lib/stream.ex:1609: Enumerable.Stream.do_each/4
    (elixir 1.10.2) lib/enum.ex:3383: Enum.reverse/1
    (elixir 1.10.2) lib/enum.ex:2982: Enum.to_list/1
    (myapp 0.1.0) lib/myapp.ex:27: MyApp.retrieve_messages/0
```

### Expected behavior

I would expect stream to keep getting more objects until they've all been processed.

**Comment by ryanwinchester** [comment]
I switched from `stream!` to `request!` because I wasn't getting that error with `request!`, refactored everything to paginate, then when we get to pass in a `marker` we get the same error.

So, the error is happening when passing in a `marker`...

**Comment by benwilson512** [comment]
Have you tried against ex_aws master?

**Comment by cjbottaro** [comment]
This issue is still happening. Explanation of the fix is here: https://github.com/ex-aws/ex_aws_s3/issues/94#issuecomment-774244892
